Repository wellington-sbr/BetterHealthProject, pull requests merged in 2025-04, with the labels that each got.

#25 Create application for each role
  .idea/BetterHealthProject.iml
  .idea/misc.xml
  BetterHealthProject/__pycache__/__init__.cpython-312.pyc
  BetterHealthProject/__pycache__/settings.cpython-312.pyc
  admin/__init__.py
  admin/admin.py
  admin/apps.py
  admin/migrations/__init__.py
  admin/models.py
  admin/tests.py
  admin/views.py
  financial/__init__.py
  financial/admin.py
  financial/apps.py
  financial/migrations/__init__.py
  financial/models.py
  financial/tests.py
  financial/views.py
  patient/__init__.py
  patient/admin.py
  patient/apps.py
  patient/migrations/__init__.py
  patient/models.py
  patient/tests.py
  patient/views.py
Labels: enhancement, Build

#34 Login and Registration for patients
  .idea/BetterHealthProject.iml
  .idea/misc.xml
  BetterHealthProject/__pycache__/__init__.cpython-313.pyc
  BetterHealthProject/__pycache__/settings.cpython-313.pyc
  BetterHealthProject/__pycache__/urls.cpython-313.pyc
  BetterHealthProject/__pycache__/wsgi.cpython-313.pyc
  BetterHealthProject/settings.py
  BetterHealthProject/urls.py
  db.sqlite3
  patient/__pycache__/__init__.cpython-313.pyc
  patient/__pycache__/admin.cpython-313.pyc
  patient/__pycache__/apps.cpython-313.pyc
  patient/__pycache__/models.cpython-313.pyc
  patient/__pycache__/urls.cpython-313.pyc
  patient/__pycache__/views.cpython-313.pyc
  patient/admin.py
  patient/migrations/__pycache__/__init__.cpython-313.pyc
  patient/static/logo.jpg
  patient/static/style.css
  patient/templates/base.html
  patient/templates/home.html
  patient/templates/login.html
  patient/templates/register.html
  patient/urls.py
  patient/views.py
Labels: enhancement, Code

#78 URL added in Allowed_Hosts
  BetterHealthProject/__pycache__/settings.cpython-313.pyc
  BetterHealthProject/settings.py
  patient/__pycache__/views.cpython-313.pyc
Labels: Release
